import{S as m,i}from"./assets/vendor-BrddEoy-.js";/* empty css                      */(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const u="47542274-6332373665e9da78801fe67b7",g="https://pixabay.com/api/";async function d(s,r=1,a=12){const t=`${g}?key=${u}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{const e=await fetch(t);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error("Error fetching images:",e.message),e}}function h(s,r){if(r.innerHTML="",s.hits.length===0){iziToast.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=s.hits.map(t=>`
    <a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" />
       <div class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" />
    </a>
  `).join("");r.insertAdjacentHTML("beforeend",a),setTimeout(()=>{lightbox.refresh()},0)}new m(".gallery a",{captionsData:"alt",captionDelay:250});const c=document.getElementById("search-form"),l=document.getElementById("gallery"),f=document.getElementById("loader");function y(){f.style.display="block"}function p(){f.style.display="none"}async function L(s){try{y();const r=await d(s);return console.log("API Response:",r),r}catch(r){throw console.error("Error fetching images:",r),r}finally{p()}}c.addEventListener("submit",async s=>{s.preventDefault(),console.log("Form submitted");const r=c.elements.query.value.trim();if(!r){i.error({title:"Error",message:"Please enter a search term."});return}l.innerHTML="";try{const a=await L(r);h(a,l)}catch(a){console.log(a),i.error({title:"Error",message:"Failed to fetch images."})}});
//# sourceMappingURL=index.js.map
